import 'package:flutter_test/flutter_test.dart';
import 'package:studyking/core/services/pdf_ingestion_service.dart';

void main() {
  group('PdfIngestionService', () {
    group('parsePdf', () {
      test('returns mock content when api key is empty', () async {
        final service = PdfIngestionService(apiKey: '');

        final result = await service.parsePdf(
          pdfContent: 'Sample PDF content',
          syllabus: 'Basic syllabus',
          modelId: 'gpt-3.5-turbo',
        );

        expect(result.isNotEmpty, isTrue);
        expect(result.first['name'], equals('Sample Topic'));
      });

      test('returns mock content on API error', () async {
        final service = PdfIngestionService(apiKey: 'invalid_key');

        final result = await service.parsePdf(
          pdfContent: 'Sample content',
          syllabus: 'Syllabus',
          modelId: 'gpt-3.5-turbo',
        );

        expect(result.isNotEmpty, isTrue);
      });
    });

    group('classifyTopic', () {
      test('returns first possible topic when api key is empty', () async {
        final service = PdfIngestionService(apiKey: '');

        final result = await service.classifyTopic(
          content: 'Some content',
          possibleTopics: ['Algebra', 'Calculus', 'Geometry'],
          modelId: 'gpt-3.5-turbo',
        );

        expect(result, equals('Algebra'));
      });

      test('returns Unclassified when no possible topics and api key empty', () async {
        final service = PdfIngestionService(apiKey: '');

        final result = await service.classifyTopic(
          content: 'Some content',
          possibleTopics: [],
          modelId: 'gpt-3.5-turbo',
        );

        expect(result, equals('Unclassified'));
      });

      test('returns first topic on API error', () async {
        final service = PdfIngestionService(apiKey: 'invalid_key');

        final result = await service.classifyTopic(
          content: 'Some content',
          possibleTopics: ['Algebra', 'Calculus'],
          modelId: 'gpt-3.5-turbo',
        );

        expect(result, equals('Algebra'));
      });
    });

    group('extractQuestions', () {
      test('returns mock questions when api key is empty', () async {
        final service = PdfIngestionService(apiKey: '');

        final result = await service.extractQuestions('Content here', 'gpt-3.5-turbo');

        expect(result.isNotEmpty, isTrue);
        expect(result.first['text'], isNotNull);
        expect(result.first['options'], isA<List>());
      });

      test('returns mock questions on API error', () async {
        final service = PdfIngestionService(apiKey: 'invalid_key');

        final result = await service.extractQuestions('Content here', 'gpt-3.5-turbo');

        expect(result.isNotEmpty, isTrue);
      });
    });

    group('generateSummary', () {
      test('returns mock summary when api key is empty', () async {
        final service = PdfIngestionService(apiKey: '');

        final result = await service.generateSummary('Content', 'Algebra', 'gpt-3.5-turbo');

        expect(result, equals('Summary of Algebra'));
      });

      test('returns LLM summary on API call', () async {
        final service = PdfIngestionService(apiKey: 'test_key');

        final result = await service.generateSummary('Content', 'Algebra', 'gpt-3.5-turbo');

        expect(result, equals('Summary generated by LLM'));
      });
    });

    });
}