// PDF Ingestion Service
import 'package:flutter/foundation.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';

class PdfIngestionService {
  final String apiKey;

  PdfIngestionService({required this.apiKey});

  Future<List<Map<String, dynamic>>> parsePdf({
    required String pdfContent,
    required String syllabus,
    required String modelId,
  }) async {
    if (apiKey.isEmpty) {
      return _getMockPdfContent(pdfContent, syllabus);
    }

    final prompt = '''
Parse this educational content and extract topics.
Content: $pdfContent
Syllabus: $syllabus

JSON response.
''';

    try {
      final response = await _callLlm(prompt, modelId);
      return _parseContent(response);
    } catch (e) {
      debugPrint('PDF Parsing Error: $e');
      return _getMockPdfContent(pdfContent, syllabus);
    }
  }

  Future<String> classifyTopic({
    required String content,
    required List<String> possibleTopics,
    required String modelId,
  }) async {
    if (apiKey.isEmpty) {
      return possibleTopics.isNotEmpty ? possibleTopics.first : 'Unclassified';
    }

    final prompt = '''
Classify content into one of: ${possibleTopics.join(', ')}
Content: $content

Return topic name.
''';

    try {
      final response = await _callLlm(prompt, modelId);
      return response.trim();
    } catch (e) {
      return possibleTopics.isNotEmpty ? possibleTopics.first : 'Unclassified';
    }
  }

  Future<List<Map<String, dynamic>>> extractQuestions(String content, String modelId) async {
    if (apiKey.isEmpty) {
      return _getMockQuestions();
    }

    final prompt = '''
Extract questions from content: $content

JSON array.
''';

    try {
      final response = await _callLlm(prompt, modelId);
      return jsonDecode(response);
    } catch (e) {
      return _getMockQuestions();
    }
  }

  Future<String> generateSummary(String content, String topicName, String modelId) async {
    if (apiKey.isEmpty) {
      return 'Summary of $topicName';
    }

    return 'Summary generated by LLM';
  }

  Future<String> _callLlm(String prompt, String model) async {
    final headers = <String, String>{
      'Content-Type': 'application/json',
      'Authorization': 'Bearer $apiKey',
    };

    final response = await http.post(
      Uri.parse('https://openrouter.ai/api/v1/chat/completions'),
      headers: headers,
      body: jsonEncode({
        'model': model,
        'messages': [
          {'role': 'system', 'content': 'Content analyzer'},
          {'role': 'user', 'content': prompt},
        ],
      }),
    );

    if (response.statusCode == 200) {
      final data = jsonDecode(response.body);
      return data['choices'][0]['message']['content'];
    } else {
      throw Exception('API Error');
    }
  }

  List<Map<String, dynamic>> _parseContent(String response) {
    try {
      final data = jsonDecode(response);
      if (data is List) return data.cast<Map<String, dynamic>>();
      if (data is Map && data['topics'] is List) return List.castFrom(data['topics']);
      return [];
    } catch (e) {
      return [];
    }
  }

  List<Map<String, dynamic>> _getMockPdfContent(String pdfContent, String syllabus) {
    return [
      {
        'name': 'Sample Topic',
        'description': 'Generated from PDF',
        'keyPoints': ['Point 1', 'Point 2'],
      },
    ];
  }

  List<Map<String, dynamic>> _getMockQuestions() {
    return [
      {
        'text': 'Sample question?',
        'options': ['A', 'B', 'C', 'D'],
        'correctAnswer': 0,
        'difficulty': 2,
      },
    ];
  }
}
